format = """
[░▒▓](#b37202)\
$username\
$os\
[](bg:#b37262 fg:#96928f)\
$status\
$localip\
$hostname\
$memory_usage\
$time\
$directory\
$container\
[](fg:#b37202)\
$git_status\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$shlvl\
$shell\
$sudo\
$package\
$ruby\
$lua\
$c\
$rust\
$perl\
$python\
$php\
$java\
$cmd_duration\
$character\
"""
right_format = """

"""
#continuation_prompt = '▶▶ '

[username]
style_user = 'bg:#b37202 bold black'
style_root = 'bg:#b37202 bold red'
format = '[💀$user]($style)'
disabled = false
show_always = true

[sudo]
style = 'bold green'
symbol = '💢'
disabled = false

[cmd_duration]
min_time = 4
show_milliseconds = true
disabled = false
style = "bold italic yellow"

[shell]
fish_indicator = '🐟'
bash_indicator = '☠️ '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan'
disabled = false

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style)'
#format = '$shlvl(s) down'
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0

[time]
disabled = true
use_12hr = true
time_format = "%I:%M%P" # Hour:Minute Format
style = "bg:#b37202 black"
format = '[⌚️$time ]($style)'

[directory]
style = "bg:#b37202 bold yellow"
format = "[:$path]($style)[$read_only]($read_only_style)"
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"
#read_only = "󰌾"

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[❯](bold red) '

[aws]
symbol = "  "

[buf]
symbol = "🦬 "

[bun]
format = 'via [🍔 $version](bold green) '

[c]
symbol = ""
format = '[ $symbol $name $version]($style)'
version_format = 'v${raw}'
detect_extensions = ['c', 'h']
#detect_files =
#detect_folders =
commands = [ [ 'cc', '--version' ], [ 'gcc', '--version' ], [ 'clang', '--version' ] ]
style = 'bold 144'
disabled = false


[conda]
symbol = " "
format = '[$symbol$environment](dimmed green) '

[container]
format = '[$symbol \[$name\]]($style) '
disabled = true

[dart]
symbol = " "
format = 'via [🔰 $version](bold red) '

[docker_context]
symbol = " "
format = 'via [🐋 $context](blue bold)'

[elixir]
symbol = '🔮 '

[elm]
symbol = " "
format = 'via [ $version](cyan bold) '

#[env_var.USER]
#default = 'unknown user'

#[env_var]
#variable = 'SHELL'
#default = 'unknown shell'

#[env_var.SHELL]
#variable = 'SHELL'
#default = 'unknown shell'
#[env_var.USER]
#default = 'unknown user'

[fill]
symbol = '-'
style = 'bold green'

[fossil_branch]
symbol = '🦎 '
truncation_length = 4
truncation_symbol = ''

[git_branch]
symbol = '🌱 '
truncation_length = 4
format = 'on [$symbol$branch(:$remote_branch)]($style) '
#truncation_symbol = ''
#only_attached = false
#branch = 'master'
#ignore_branches = ['master', 'main']
remote_name = "https://gitlab.com/Funkin/Mofo"
remote_branch = "Mofo"
style = 'bold purple'
disabled = true

[git_state]
format = '([\[$all_status$ahead_behind\]]($style))'
#ahead = "🏎💨"
#behind = "⇣${count}"
#diverged = "⇕⇡${ahead_count}⇣${behind_count}"
#renamed = "r"
#deleted = "🗑"
style = "cyan"
#conflicted = "​🏳"
#untracked = "​🤷"
#modified = "​📝"
#staged = '[++\($count\)](green)'
#stashed = "📦"
#up_to_date = '✓'
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = '[🍒 PICKING](bold red)'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
disabled = false

[git_commit]
tag_symbol = " 🔖"
format = '[\($hash$tag\)]($style) '
style = 'bold green'
only_detached = true
disabled = false

[git_metrics]
added_style = 	'bold green'
deleted_style = 'bold red'
only_nonzero_diffs = true
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
disabled = true
ignore_submodules = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '🏳${count}'
ahead = '🏎💨⇡${count}'
behind = '😰⇣${count}'
diverged = '😵⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = '✓'
untracked = '🤷${count}'
stashed = '📦${count}'
modified = '📝${count}'
staged = '[++\($count\)](green)'
renamed = '👅${count}'
deleted = '🗑${count}'
#typedchanged = ''
style = 'bold red'
ignore_submodules = false
disabled = false


[golang]
symbol = " "

[guix_shell]
symbol = " "
disabled = true
format = 'via [🐂](yellow bold) '

[haskell]
symbol = " "

[haxe]
symbol = " "
format = "via [⌘ $version](bold fg:202) "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "
ssh_only = false
format = '[$ssh_symbol](bg:#b37202 bold blue)@[$hostname](bg:#b37202 bold white)'
trim_at = '.companyname.com'
disabled = true

[java]
symbol = "🌟 "
format = '[░▒▓${symbol}(${version})▓▒░]($style)'
version_format = 'v${raw}'
detect_extensions = ['java', 'class', 'gradle', 'jar', 'cljs', 'cljc']
detect_files = ['pom.xml', 'build.gradle.kts', 'build.sbt', '.java-version', 'deps.edn', 'project.clj', 'build.boot', '.sdkmanrc']
style = 'bg:#b37262 red dimmed'
disabled = false


[julia]
symbol = " "

[localip]
ssh_only = false
style = "bg:#b37202"
format = '@[$localipv4](bold red) '
disabled = true

[lua]
symbol = "🌙 "
format = '[ $symbol$version]($style) '
style = 'bold blue'
version_format = 'v${raw}'
detect_extensions = ['lua']
detect_files = ['.lua-version']
detect_folders = ['lua']
lua_binary = 'lua'
disabled = false

[memory_usage]
disabled = true
threshold = -1
style = 'bg:#b37202 bold white'
symbol = "󰍛"

[meson]
disabled = false
truncation_symbol = '--'
symbol = "󰔷 "
style = 'bold dimmed green'

[nim]
style = 'yellow'
symbol = '🎣 '

[nix_shell]
symbol = " "
disabled = true
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [☃️ $state( \($name\))](bold blue) '

[nodejs]
symbol = " "
format = 'via [🤖 $version](bold green) '

[os]
format = "[$symbol]($style)"
style = "bg:#b37202 bold blue"
disabled = false

[os.symbols]
Alpaquita = "🔔 "
Alpine = "🏔️ "
Amazon = "🙂 "
Android = "🤖 "
Arch = "🎗️ "
Artix = "🎗️ "
CentOS = "💠 "
Debian = "🌀 "
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = "🚀 "
Fedora = "🎩 "
FreeBSD = "😈 "
Garuda = "🦅 "
Gentoo = "🗜️ "
HardenedBSD = "🛡️ "
Illumos = "🐦 "
Linux = "🐧 "
Mabox = "📦 "
Macos = "🍎 "
Manjaro = "🥭 "
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = "🌿 "
NetBSD = "🚩 "
NixOS = "❄️ "
OpenBSD = "🐡 "
OpenCloudOS = "☁️ "
openEuler = "🦉 "
openSUSE = "🦎 "
OracleLinux = "🦴 "
Pop = "🍭 "
Raspbian = "🍓 "
Redhat = "🎩 "
RedHatEnterprise = "🎩 "
Redox = "🧪 "
Solus = "⛵ "
SUSE = "🦎 "
Ubuntu = "🎯 "
Unknown = "❓ "
Windows = "🪟 "

[package]
symbol = "󰏗 "
format = 'via [🎁 $version](208 bold) '

[perl]
format = '[🔮 $version]($style) '
version_format = 	'v${raw}'
detect_extensions = ['pl', 'pm', 'pod']
detect_files = ['Makefile.PL', 'Build.PL', 'cpanfile', 'cpanfile.snapshot', 'META.json', 'META.yml', '.perl-version']
style = 'bold 149'



[php]
symbol = '🐘'
format = '[$symbol($version )]($style)'
version_format = 'v${raw}'
detect_extensions = ['php']
detect_files = ['composer.json', '.php-version']
style = '147 bold'


[pijul_channel]
symbol = " "

[python]
symbol = '⚕️ '
#pyenv_version_name = true
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
version_format = 'v${raw}'
style = 'bold yellow'
detect_extensions = ['py']
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']

#disabled = false

[rlang]
symbol = "󰟔 "

[ruby]
symbol = "🔺 "
format = '[$symbol($version )]($style)'
detect_files = ['Gemfile', '.ruby-version']
#detect_folders = []
detect_variables = ['RUBY_VERSION', 'RBENV_VERSION']
detect_extensions = ['rb']
disabled = false
style = 'bold red'

[rust]
symbol = "🦀 "
version_format = 'v${raw}'
format = '[⚙️ $version](red bold)'
detect_extensions = ['rs']
detect_files = ['Cargo.toml']
style = 'red'


[scala]
symbol = " "

[status]
style = "bg:#b37202 bold white"
symbol = '🔴'
success_symbol = '🟢SUCCESS'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)'
map_symbol = true
disabled = true


