alias nowplaying='playerctl metadata --format "Now playing: {{ artist }} - {{ title }}" '
alias reload='source ~/.bashrc && source ~/.bash_aliases'
alias myip='curl ipinfo.io/ip'
alias lt='ls --human-readable --size -1 -S --classify'
alias lc='ls --color=auto'
alias dir='ls'
alias copy='cp'
alias move='mv'
alias gerp='echo "You did it *again*!"; grep'
alias sl='ls'
alias localip="ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'"
alias clearmem='sync; sudo sysctl vm.drop_caches=3'
alias nf='neofetch --battery_display --ascii_distro Ubuntu_small'
alias glavdesk='glava --desktop'
alias scanner='sudo nmap -O -f -oN /home/myrr/scanresult'
alias checknet='sudo slurm -z -s -d 1 -i wlan0'
alias glance='sudo glances --cconfig  /home/myrr/.config/glances.conf'
alias ..='cd ..' 
alias home='cd /home/myrr'
