#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
 bootstrap_before = 'myspacevim#before'
#   bootstrap_after = 'myspacevim#after'
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
#hi Comment cterm=italic 
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 1 
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true 
    enable_vimfiler_welcome = false
    filetree_direction = "left"
#guifont = "JetBrainsMono Nerd Font:h11"

#statusline_left_sections = [
#   'winnr',
#   'major mode',
#   'filename',
#   'fileformat',
#   'minor mode lighters',
#   'version control info',
#   'search status'
#   ]
#   statusline_right_sections - [
#   'cursorpos',
#    'percentage',
#   'input method',
#   'date',
#   'time'
#   ]
#automatic_update = true
# Enable autocomplete layer
[[layers]]
#name = "colorscheme"
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]
repo = 'https://github.com/vifm/vifm.vim'
merged = false
repo = 'lifepillar/vim-colortemplate'
merged = false
repo = 'scrooloose/nerdtree'
merged = false
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
merged = false
repo = 'Xuyuanp/nerdtree-git-plugin'
merged = false
repo = 'scrooloose/nerdcommenter'
merged = false
repo = 'khaveesh/vim-fish-syntax'
merged = false
repo = 'sainnhe/sonokai'
merged = false
repo = 'ryanoasis/vim-devicons'
merged = false
repo = 'amadeus/vim-css'
merged = false
repo = "Fymyte/rasi.vim"
merged = false
repo = 'ghifarit53/tokyonight-vim'
merged = false
repo = "ap/vim-css-color"
merged = false
#repo = 'vim-airline/vim-airline-themes'
#merged = false
#repo = 'vim-airline/vim-airline'
#merged = false
