alias nowplaying='playerctl metadata --format "Now playing: {{ artist }} - {{ title }}" '
alias reload='source ~/.bashrc && source ~/.bash_aliases'
alias myip='curl ipinfo.io/ip'
alias lt='ls --human-readable --size -1 -S --classify'
alias lc='ls --color=auto'
alias dir='ls'
alias copy='cp'
alias move='mv'
alias gerp='echo "You did it *again*!"; grep'
alias sl='ls'
alias localip="ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'"
alias clearmem='sync; sudo sysctl vm.drop_caches=3'
alias nf='neofetch'
alias glavdesk='glava --desktop'
alias mp3stream="cvlc -vvv pulse://alsa_output.pci-0000_00_1b.0.analog-surround-51.monitor --sout \
'#transcode{acodec=mpga,ab=128,channels=2}:standard{access=http,dst=192.168.1.73:8080/pc.mp3}'"
alias checknet='sudo slurm -z -s -d 1 -i eno1'
alias checkwifi='sudo slurm -z -s -d 1 -i wlp3s0'
alias frem='free -m -h'
alias ..='cd ..'
alias path='echo -e ${PATH//:/\\n}'
alias ports='sudo netstat -tulanp > /home/myrrdin/Documents/Ports.txt'

alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
alias metasploit='cd /opt/metasploit-framework/bin/'
alias console='sudo msfconsole'
alias home='cd /home/myrrdin'
alias sysinfo='sudo inxi -Fxz > /home/myrrdin/Documents/SysInfo.txt'
alias glavrad='glava --desktop --entry=customrad.glsl --force-mod=radial'
alias glavcir='glava --desktop --entry=customrad.glsl --force-mod=circle'
alias lk='exa -al --color=always --group-directories-first'
alias aptu='sudo apt update && sudo apt upgrade'
alias aptd='sudo SKIP_AUTOSNAP= apt update'
alias aptg='sudo SKIP_AUTOSNAP= apt upgrade'
alias aptr='sudo SKIP_AUTOSNAP= apt remove'
alias nsong='audacious --fwd'
alias lsong='audacious --rew'
alias nwp='nowplaying'
alias mach='/home/myrrdin/macchina/target/release/./macchina'
alias scannet='sudo iftop -n -b -p -P -B'
