# Hydrogen

spacing         = 2
padding         = 0
hide_ascii      = true
separator       = "ᐉ"
key_color       = "Yellow"
separator_color = "gray"

[palette]
type = "Full"
visible = false

[bar]
glyph           = "⌘"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
border          = "double"
visible         = true


[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
distro          = "Distro"
OS              = "OperatingSystem"
kernel          = "Kernel"
de              = "DE"
wm              = "WM"
terminal        = "Terminal"
shell           = "Shell"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
disk_space      = "Disk Space"
